apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: validator-v2
spec:
  replicas: 3
  strategy:  
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: validator
        version: "v2"
    spec:
      containers:
        - name: validator
          image: 'docker.io/nitinsingh01/val-uid:v2'
          ports:
            - containerPort: 8080
            
          readinessProbe: 
            httpGet:
              path: /Hello
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 100
            
