apiVersion: v1
kind: Service
metadata:
  name: validator
  labels:
    name: validator
    version: "v2"
    
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: validator
    version: "v2"
  type: LoadBalancer