apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: validator-v1
spec:
  replicas: 3
  strategy:  
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: validator
        version: "v1"
    spec:
      containers:
        - name: validator
          image: 'docker.io/nitinsingh01/val-uid:v1'
          ports:
            - containerPort: 8080
            
          readinessProbe: 
            httpGet:
              path: /Hello
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            
---
apiVersion: v1
kind: Service
metadata:
  name: validator
  labels:
    name: validator
    version: "v1"
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: validator
    version: "v1"
  type: LoadBalancer